//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowersShop.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Cart_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Users Users { get; set; }
    }
}
