//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowersShop.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Presentation
    {
        public int Category_Presentation_ID { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> Presentation_ID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Presentation Presentation { get; set; }
    }
}
