//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowersShop.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Discount
    {
        public int Order_Discount_ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<int> Discount_ID { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual Order Order { get; set; }
    }
}
