//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowersShop.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_ID { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Payment_Method { get; set; }
        public Nullable<int> Order_ID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
